// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlkPQkFuK7Ws7bq81DMPQ7uohdA6LftLg',
    appId: '1:480451327287:web:55d29b32dffac1896596b2',
    messagingSenderId: '480451327287',
    projectId: 'qbit-f228a',
    authDomain: 'qbit-f228a.firebaseapp.com',
    storageBucket: 'qbit-f228a.appspot.com',
    measurementId: 'G-2HEXF9TD5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3kgTHJSEdiwN2YoD-0d6Cp9CsjILtl7I',
    appId: '1:480451327287:android:3f1b5a66927ea4cf6596b2',
    messagingSenderId: '480451327287',
    projectId: 'qbit-f228a',
    storageBucket: 'qbit-f228a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2a3chqGisW_MqCsfMi8gzybOK-UxWvE',
    appId: '1:480451327287:ios:bbfca898169777306596b2',
    messagingSenderId: '480451327287',
    projectId: 'qbit-f228a',
    storageBucket: 'qbit-f228a.appspot.com',
    iosClientId: '480451327287-0p51cs33jdiljr65pgf8rn1v886dh8g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.qbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2a3chqGisW_MqCsfMi8gzybOK-UxWvE',
    appId: '1:480451327287:ios:bbfca898169777306596b2',
    messagingSenderId: '480451327287',
    projectId: 'qbit-f228a',
    storageBucket: 'qbit-f228a.appspot.com',
    iosClientId: '480451327287-0p51cs33jdiljr65pgf8rn1v886dh8g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.qbit',
  );
}
